swagger: '2.0'
info:
  version: v1
  title: client
  description: cl
host: 'localhost:2002'
basePath: /api
schemes:
  - https
produces:
  - application/json
paths:
  /clients/v1:
    get:
      tags:
        - Client
      description: Gets all clients from the system that the user has access to
      operationId: getClient
      produces:
        - application/json
      x-swagger-router-controller: Client
      responses:
        '200':
          description: client response
          schema:
            type: array
            items:
              $ref: '#/definitions/clientsv1'
        '404':
          description: client response
          schema:
            type: object
        '500':
          description: client response
          schema:
            type: object
      parameters:
        - name: pageSize
          in: query
          description: Number of records returned
          type: integer
        - name: pageNumber
          in: query
          description: Page number
          type: integer
    put:
      tags:
        - Client
      description: Puts all clients from the system that the user has access to
      operationId: putClient
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Client
      responses:
        '204':
          description: client response
          schema:
            type: array
            items:
              $ref: '#/definitions/clientsv1'
        '404':
          description: client response
          schema:
            type: object
        '500':
          description: client response
          schema:
            type: object
      parameters:
        - name: clients/v1
          in: body
          schema:
            $ref: '#/definitions/clientsv1'
    post:
      tags:
        - Client
      description: Posts all clients from the system that the user has access to
      operationId: postClient
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Client
      responses:
        '204':
          description: client response
          schema:
            type: array
            items:
              $ref: '#/definitions/clientsv1'
        '404':
          description: client response
          schema:
            type: object
        '500':
          description: client response
          schema:
            type: object
      parameters:
        - name: clients/v1
          in: body
          schema:
            $ref: '#/definitions/clientsv1'
    patch:
      tags:
        - Client
      description: Patchs all clients from the system that the user has access to
      operationId: patchClient
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Client
      responses:
        '204':
          description: client response
          schema:
            type: array
            items:
              $ref: '#/definitions/clientsv1'
        '404':
          description: client response
          schema:
            type: object
        '500':
          description: client response
          schema:
            type: object
    delete:
      tags:
        - Client
      description: Deletes all clients from the system that the user has access to
      operationId: deleteClient
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Client
      responses:
        '204':
          description: client response
          schema:
            type: array
            items:
              $ref: '#/definitions/clientsv1'
        '404':
          description: client response
          schema:
            type: object
        '500':
          description: client response
          schema:
            type: object
      parameters:
        - name: clients/v1
          in: body
          schema:
            $ref: '#/definitions/clientsv1'
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  clientsv1:
    type: object
    properties:
      name:
        type: string
      age:
        type: number
    required:
      - name
      - age
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
          tls-profile: ''
          secure-gateway: false
    catch: []
